### ISSUE TITLE
Documentation for DDG

### ISSUE THREAD

**Issue by riyadparvez** [angr/angr-doc#1]
From Data Dependency Graph analysis, there are no documentation provided. It would be great if you can provide some documentation on analysis and implementation for that analysis.

**Comment by ltfish** [comment]
A little update: I'm rewriting `DDG` (with many comments). You can at least read through all my comments after the new version is done and merged to master!

**Comment by Manouchehri** [comment]
@ltfish Any update on this? [`analyses.md#ddg`](https://github.com/angr/angr-doc/blob/master/docs/analyses.md#ddg) is still only a "TODO" box.
