### ISSUE TITLE
angr for type inference

### ISSUE THREAD

**Issue by bsmondal** [angr/angr-doc#11]
Hi,
I found that angr is able to detect type through static analysis ( *full-program static analysis (i.e., type inference, program slicing)*). Could you please give an example that how anrg can be use for type inference?

Thank you for your support and time.

**Comment by zardus** [comment]
We did used to have a type inference engine (based on TIE - http://users.ece.cmu.edu/~aavgerin/papers/tie-ndss-2011.pdf), but that code has atrophied as angr evolved, and the capability no longer exists. Resurrecting that is definitely on our TODO list, but we haven't gotten to it yet.

angr *can* do program slicing. If you're interested just in slicing, but not in type inference, we can try to put together an example.

**Comment by ltfish** [comment]
Type inference on binaries is still a difficult problem right now. Although there are many papers claiming good results, I'm not aware of any paper that can yield results good enough for practical binary analysis. This is one of the reasons why type inference no longer exists in angr.

Saying that, we will be extremely happy if you can implement type inference for angr :-)

**Comment by bsmondal** [comment]
Thanks for inspiring me.  Well, I am looking for to implement such solution, but initially it will be limited to C basic data type (int float char shot...). I went through TIE , REWARDS and also few other papers where they are only focusing C data type. Now I am planing to write a tool on top of angr. So, could you please give an example of VSA anlysis and program slicing by angr. 

Finally, any suggestion which can lead me to ahead of this problem will be highly appreciated.

**Comment by ltfish** [comment]
You may also take a look at Howard[1] for struct recovery.

[1] Howard: a Dynamic Excavator for Reverse Engineering Data Structures, Asia Slowinska, etc. http://www.isoc.org/isoc/conferences/ndss/11/pdf/5_1.pdf

**Comment by ltfish** [comment]
For program slicing, I'll compose an example in the next few days and put it in angr-doc.

**Comment by bsmondal** [comment]
I already checked Howard. Thanks. Waiting for ur example :)

**Comment by bsmondal** [comment]
Hi ltfish,

I would be grateful if you update doc with the program slicing example ? Thank you.

**Comment by ltfish** [comment]
@bsmondal I'm on a short trip right now, and don't really have regular Internet access :-( I was planning to work on documentation once I'm back to school.

As a start, you may take a look at methods in `angr/tests/test_slicing.py`. To construct a program slice, you should construct a control flow graph (CFG), a control dependence graph (CDG, which is derived from CFG), and a data dependence graph (DDG or VSA_DDG. The latter requires VSA). If you only have a CFG, you can also construct a CFG-only slice.

I believe the full slicing not working correctly sometimes right now, and fixing that is definitely on my TODO list.

**Comment by bsmondal** [comment]
Thank you very much. I am starting from your suggested point and will wait for your complete post. Have a nice trip. :)

**Comment by ronnychevalier** [comment]
There is a beginning of documentation in [here](/angr/angr-doc/blob/master/analyses/backward_slice.md)

**Comment by bsmondal** [comment]
Thank you very much. I will go through your documentation and try to do it from my side. Let you know if I found any difficulties. :D
