### ISSUE TITLE
secuinside2016mbrainfuzz uses function_manager

### ISSUE THREAD

**Issue by Manouchehri** [angr/angr-doc#114]
`function_manager` no longer exists, so the example doesn't work. https://github.com/angr/angr/issues/195

Reported in https://lists.cs.ucsb.edu/pipermail/angr/2017-January/000278.html

**Comment by zardus** [comment]
We need to figure out something to do with these long-running examples in terms of CI. For now, we'll have to get around to fixing this eventually :-)
