### ISSUE TITLE
docker root permissions

### ISSUE THREAD

**Issue by zhouat** [angr/angr-doc#126]
i use the docker for angr( angr/angr ), it works well. now i want to update some library, can you give us the passwd for root then?

**Comment by zardus** [comment]
There's no password for root, and unfortunately, sudo isn't installed. There are two routes you can take:

1. It's a docker container, so you can derive off of it in a new Dockerfile. (using `FROM angr/angr`)
2. A PR that adds sudo (and passwordless sudo access to the angr user) would be cool as well.

**Comment by zhouat** [comment]
thxs very much. @zardus

**Comment by alrawi** [comment]
I would add a third option

`docker start angr
docker exec -ti -u root angr bash`

**Comment by ltfish** [comment]
@alrawi it's something that should probably go into angr-docs. Do you want to make a PR for that?
