### ISSUE TITLE
How to re-solve the constraints when the constraints or pre-constraints are changed

### ISSUE THREAD

**Issue by leithon** [angr/angr-doc#133]
Dear all,

I want to make the generated input be similar with the given input as much as possible.
To implement it, what I thought is to remove the replacements of input preconstraints one by one, and then to ask the solver SolverReplacement to solve repeatedly.

Is there an API function that can be used to re-solve the constraints when the constraints or pre-constraints are changed?

Thank you very much.

**Comment by ltfish** [comment]
Solving methods in SimuVEX take an argument called `extra_constraints`. For example, you can do `state.se.any_int(your_ast_goes_here, extra_constraints=(my_input_byte_0=0x20,))`. Is this what you want?

**Comment by leithon** [comment]
Thank you Fish,

I am reading the source code of driller. 
In the tracer.py souce code, the remove_preconstraints() function disables the so.ReplacementSolver opiton and reloads another solver to remove preconstriants.
This method removes all the preconstraints.

What I thought is to remove just a part of them, and then could angr return the satisiable() for the remaining preconstraints.

I noticed that in the solver of Replacement, it defines a dict to store the constraints for replacement in solving.
I just removed items  in the dict, but state.se.satisfiable() still returns False.



ZHAO Lei
Phone: +86-13407188699
School of Computer , Wuhan University, Hubei, 430072, China
 
From: Fish
Date: 2017-04-26 16:49
To: angr/angr-doc
CC: leithon; Author
Subject: Re: [angr/angr-doc] How to re-solve the constraints when the constraints or pre-constraints are changed (#133)
Solving methods in SimuVEX take an argument called extra_constraints. For example, you can do state.se.any_int(your_ast_goes_here, extra_constraints=(my_input_byte_0=0x20,)). Is this what you want?

**Comment by salls** [comment]
Use the `remove_replacements` function. You should not add or remove from that dictionary directly.
