### ISSUE TITLE
Example script question

### ISSUE THREAD

**Issue by kennynaoh** [angr/angr-doc#136]
Hello, I am a beginner of angr, also a beginner of symbolic execution. I think it's better to learn angr by reading a example script and running it. There is a question want to ask. I read some of example angr script under `angr-doc/examples/` and I found that there are almost no source code just compiled file. The question is how do I know how to do the symbolic execution with no source code. For example, the script for `CSCI-4968-MBE/challenges/crackme0x01/`, how do I know the `FIND_ADDR` is equal to `0x0804844e` and `AVOID_ADDR` is equal to `0x08048434` to set into the `path_group.explore`? Sorry for my basic question. Thanks!

**Comment by zardus** [comment]
In these cases, an manual analysis was carried out to find the points to reached (using angr-management, poking around with angr's CFG in ipython, or using gdb, IDA, Binja, radare2, etc). Other examples (such as https://github.com/angr/angr-doc/blob/master/examples/CSCI-4968-MBE/challenges/crackme0x05/solve.py) have an approach without manual analysis, but frequently, the behavior that you're looking to trigger in a binary has no simple-to-detect external effects.

The examples here right now are a bit frustrating in the sense that they're not really examples of how we use angr in the course of our research, but how we sometimes use it in CTF (where the goal is to get the flag through any means necessary, not to showcase angr), so they're fairly shallow and synthetic.

**Comment by kennynaoh** [comment]
Thank you very much. Hope I can get into it shortly. ^^
