### ISSUE TITLE
exemple strcpy_find error

### ISSUE THREAD

**Issue by blackndoor** [angr/angr-doc#139]
Hello,
I'm trying to use your strcpy_find exemple but I get an error
`Exception: No address found for function : strcpy`

I modified the getFuncAddress() function to see what happens as follow
>    	for addr,func in cfg.kb.functions.iteritems():
>    		if funcName == func.name:
>    			print "addr: "+hex(addr)
>    			print "func.name: "+ func.name
>    			print "funcName: "+funcName
>    			print func.is_plt

result
> addr: 0x1000010L
> func.name: strcpy
> funcName: strcpy
> False

Do you have an idea of ​​where the problem may come from ?
Thanks in advance

**Comment by schieb** [comment]
I am not able to reproduce this.

Could you reinstall angr from github using a clean virtual environment and try again?

**Comment by rhelmot** [comment]
I am also unable to reproduce this. Closing for this and also, like, 7 months of inactivity
