### ISSUE TITLE
Example defcon2016quals babyre0 is currently broken

### ISSUE THREAD

**Issue by ltfish** [angr/angr-doc#142]
Not sure what we did to break it, bit it is currently broken.

**Comment by UnnameMax** [comment]
I was currently get the same problem too,and I am a new beginner of angr. Have you solved this problem?And I notice that the script was updated three months ago and the execute file was updated one year ago.Why did the new script get the wrong answer?

**Comment by rhelmot** [comment]
I really don't know what changed to break this. All I did to fix it was hook scanf to directly yield some symbolic variables instead of forcing us to parse them out of stdin. We really need to evaluate how we've implemented scanf and make some compromises about how shit gets represented.
