### ISSUE TITLE
API-doc are broken

### ISSUE THREAD

**Issue by zzrcxb** [angr/angr-doc#148]
These pages can only display titles:
[angr](http://angr.io/api-doc/angr.html)
[simuvex](http://angr.io/api-doc/simuvex.html)
[pyvex](http://angr.io/api-doc/pyvex.html)

I tried to visit these pages with different browsers and IPs. I can only get titles.

**Comment by rhelmot** [comment]
This happened because SOMEONE (@zardus) did a hasty release without being in the angr virtualenv. We're still recovering from DEFCON right now, but we'll fix this on Monday.

**Comment by zardus** [comment]
Fixed, thanks!
