### ISSUE TITLE
no simgr in AngrObjectFactory

### ISSUE THREAD

**Issue by JohnnyLChang** [angr/angr-doc#150]
Hi, 

during testing angr, I encountered following issue and I cannot find any workaround.

AttributeError                            Traceback (most recent call last)
<ipython-input-5-b657c454d9f6> in <module>()
----> 1 simgr = proj.factory.simgr(state)

AttributeError: 'AngrObjectFactory' object has no attribute 'simgr'

How do I solve this problem?

Johnny

**Comment by zardus** [comment]
It looks like you're mixing the last stable release of angr (on pip) and the staged development version (on github). Right now, with angr 7 about to be released, there are API incompatibilities between the two...

**Comment by JohnnyLChang** [comment]
I used virtualenv and install the stable release angr-6.7.7.31

(angr) johnny@johnny-ThinkPad-T460s:/media/sdcard/angr$ python solve.py 
WARNING | 2017-08-17 22:04:10,018 | claripy | Claripy is setting the recursion limit to 15000. If Python segfaults, I am sorry.
WARNING | 2017-08-17 22:04:10,455 | cle.blob | No custom_entry_point was specified for blob, assuming 0
Traceback (most recent call last):
  File "solve.py", line 101, in <module>
    main()
  File "solve.py", line 62, in main
    sm = project.factory.simgr(state)
AttributeError: 'AngrObjectFactory' object has no attribute 'simgr'
(angr) johnny@johnny-ThinkPad-T460s:/media/sdcard/angr$ 

I still encountered the same problem. did I do anything wrong?
sorry for silly question....

**Comment by ltfish** [comment]
> and install the stable release angr-6.7.7.31

The version on PyPI is the old release. If you want to use the new API, you'll want to install the latest version of *everything* from GitHub directly. You can use [angr-dev](https://github.com/angr/angr-dev.git) to setup a development install, which installs angr from GitHub.

Sorry for the confusion. We are almost done with this big refactor!

**Comment by JohnnyLChang** [comment]
Got it, thank you so much

**Comment by MERCEmentre** [comment]
Hello @ltfish . I stumbled upon the same issue as the original poster. I installed angr 6.7.7.31 using PIP and I'm reading the documentation on the web, which apparently is a new version for angr 7. How can I get the documentation of the version installed by PIP?

**Comment by rhelmot** [comment]
Clone this repository, look through the commit history, and check out the version from June 9, 2017.

**Comment by rhelmot** [comment]
Actually, you know what, github works just as well for this purpose. [Here you go!](https://github.com/angr/angr-doc/blob/95b0499c4bc0c6d2191b7cf1a3f944eea97ca5bd/SUMMARY.md)

**Comment by rhelmot** [comment]
...so apparently the Examples page of the docs includes hard links to the master branch :| I'm going to have to trust you you to manually navigate up the tree into the examples folder when you want to look at the examples.

**Comment by ltfish** [comment]
@rhelmot Let's ... release a new version soon.

**Comment by MERCEmentre** [comment]
Thanks @rhelmot and @ltfish! In the meantime, I managed to install a development version to be able to follow the tutorials more easily and be future proof. Thanks again!
