### ISSUE TITLE
Grub example: 'module' object has no attribute SIM_PROCEDURES

### ISSUE THREAD

**Issue by nevilad** [angr/angr-doc#153]
Hi,

The "Grub "back to 28" bug" example ends with error 'module' object has no attribute SIM_PROCEDURES.

**Comment by rhelmot** [comment]
The code you're trying to run targets the prerelease of angr 7, which is only available on github. We are finalizing the release before it gets pushed to pip, but angr-doc currently supports the new version and not the old version.

If you don't want to wait for when we release angr 7 (hopefully in the next few days), you can either install angr from github or can check out an old revision of the docs from before the refactor began, probably from early June would be a safe bet.
