### ISSUE TITLE
Is there any example about symbolizing network package?

### ISSUE THREAD

**Issue by delphi0127** [angr/angr-doc#154]
I want to analyze a mips firmware， Is there any example about symbolizing network package?

**Comment by ltfish** [comment]
I don't think I understand your question.

**Comment by Manouchehri** [comment]
See https://github.com/angr/angr-doc/blob/master/examples/flareon2015_5/solve.py for handling network traffic, and look at https://github.com/Manouchehri/angr-doc/blob/qemu-system-blob/examples/qemu-system-blob/solve.py for loading firmware blobs.
