### ISSUE TITLE
How to implement a syscall

### ISSUE THREAD

**Issue by beraphin** [angr/angr-doc#161]
Hello, I want to implement getrusage in x86, and I've add getrusage in 
**/angr/angr/procedures/definitions/linux_kernel.py** with number 77, 
then I've add a file named "getrusage.py " in  **/angr/angr/procedures/linux_kernel/** , after that I tested it, the log just changed from **"unsupported syscall_77"** to **"unsupported syscall: getrusage"**, getrusage.py wasn't executed, what's wrong with it?

**Comment by ltfish** [comment]
How is your `getrusage` implemented? Is there a class `getrusage` in `getrusage.py`?

**Comment by rhelmot** [comment]
note that documenting this specifically is very high up on my todo list - I'll reopen this issue to track that. However as fish mentioned, the problem is probably that the name of the file isn't what matters, it's the name of the class that matters.

**Comment by rhelmot** [comment]
https://docs.angr.io/extending-angr/environment#syscalls
