### ISSUE TITLE
wipe surveyors from the face of the docs

### ISSUE THREAD

**Issue by rhelmot** [angr/angr-doc#163]
- [ ] examples/ekopartyctf2016_rev250/solve.py
- [ ] examples/ekopartyctf2016_sokohashv2/sokosolver.py
- [ ] examples/google2016_unbreakable_1/solve.py
- [ ] examples/0ctf_momo_3/solve.py
- [ ] examples/asisctffinals2015_license/solve.py
- [ ] examples/defcamp_r200/solve.py
- [ ] examples/defcamp_r100/solve.py
- [ ] examples/asisctffinals2015_fake/solve.py
- [ ] examples/cmu_binary_bomb/solve.py
- [ ] examples/layer7_onlyone/solve.py
- [ ] examples/whitehatvn2015_re400/solve.py

**Comment by ltfish** [comment]
Someone should implement slicecutor as an exploration technique, and I'm ok with wiping surveyors from the Earth.

**Comment by zardus** [comment]
Agreed. I just opened https://github.com/angr/angr/issues/758 for that, @ltfish.

**Comment by rhelmot** [comment]
BOOYEAH
