### ISSUE TITLE
codegate_2017-angrybird example not working

### ISSUE THREAD

**Issue by MarkMankins** [angr/angr-doc#166]
My build of angr-dev on Ubuntu 16.04.3 fails to run codegate_2017-angrybird to completion.

If I change FIND_ADDR to 0x40119a, I do get a result.

If I change FIND_ADDR to the next block, 0x4011d6, I get an error (no states in found stash.)

Is it possible that just my build is broken or are others seeing this issue as well?

How would one go about trying to determine what is wrong if this is indeed an angr issue?

**Comment by schieb** [comment]
You can access the errored states from the simulation manager.

Please post the output of `simulation_manager.errored[0].error`. As well as any other error messages in the `errored` array if they are different.

You can debug the errored states interactively by doing `simulation_manager.errored[0].debug()`

**Comment by MarkMankins** [comment]
Actually, I'm ending up with 41 deadended states - which seems plausible.  There are no error states.

\>>>> sm.errored
[]

The error that I'm getting is that solve.py assumes there is at least one found state.

sm.found[-1] throws an IndexError.

**Comment by ltfish** [comment]
It's possible that you encountered a non-deterministic behavior somewhere in angr internals, which led to the desired state not being found. Based on your description, I think the constraint created by executing block 40119a somehow caused a conflict with other constraints.

Can you post the constraints in your state at 0x40119a, as well as the constraints in your state at 0x4011c2 (given that it cannot reach 0x4011d6 with a satisfiable state)? You can access the constraints that a state owns by doing `state.se.constraints`. There might be quite a few constraints though, so you may want to put them in a file and then upload it here.

**Comment by MarkMankins** [comment]
```
>>>> START_ADDR = 0x4007c2
>>>> FIND_ADDR = 0x40119a  
>>>> import angr
>>>> proj = angr.Project('angrybird', load_options={"auto_load_libs": False})
>>>> state = proj.factory.entry_state(addr=START_ADDR)
>>>> sm = proj.factory.simulation_manager(state)  
>>>> sm.explore(find=FIND_ADDR)
<SimulationManager with 5 active, 35 deadended, 1 found>
>>>> sm.stash(from_stash="active", to_stash="ignore")
<SimulationManager with 35 deadended, 1 found, 5 ignore>
>>>> sm.stash(from_stash="found", to_stash="active")
<SimulationManager with 1 active, 35 deadended, 5 ignore>
>>>> sm.active[0].se.constraints
[snip]
>>>> sm.step()
<SimulationManager with 1 active, 35 deadended, 5 ignore>
>>>> sm.active[0]
<SimState @ 0x4011c2>
>>>> sm.active[0].se.constraints
[snip]
```
[0x4011c2.gz](https://github.com/angr/angr-doc/files/1511592/0x4011c2.gz)
[0x40119a.gz](https://github.com/angr/angr-doc/files/1511593/0x40119a.gz)

**Comment by MarkMankins** [comment]
Constraining standard input to 21 bytes results in the same outcome with much less constraints.
[0x4011c2.gz](https://github.com/angr/angr-doc/files/1514323/0x4011c2.gz)
[0x40119a.gz](https://github.com/angr/angr-doc/files/1514324/0x40119a.gz)

**Comment by MarkMankins** [comment]
I reinstalled to a cpython virtualenv and the example worked.
I then reinstalled to a pypy virtualenv and the example didn't work in that environment.

Are there known issues running angr under pypy?

**Comment by rhelmot** [comment]
angr works fine under pypy. Our test suite runs under pypy and most developers have a default development environment which uses pypy.

**Comment by rhelmot** [comment]
I was, however, able to reproduce the exact situation you described, though, with pypy erroring out and cpython succeeding. I will investigate.

**Comment by rhelmot** [comment]
To the best of my ability this looks like an issue where the solver script was written with the assumption that angr will concretize arbitrary unconstrained symbolic values consistently, which is not the case. This shouldn't be assumed even within a single python implementation, but it looks like for whatever reason it is working consistently.

@Manouchehri this looks like your script so I'm gonna pass this one on to you.

**Comment by Manouchehri** [comment]
@MarkMankins Could you tell me how to setup/use PyPy inside the official angr/angr Docker image (Ubuntu)?

 (tbh since it works for me already, not interested in spending much time trying to make a broken environment. Hopefully that's understandable.)

```bash
dave@ubuntu:~$ docker -H 10.0.0.33:2376 --tls run -it --rm --memory 28gb --cpuset-cpus 16 --network dock angr/angr
(angr) angr@508780408adf:~$ cd angr-dev/angr-doc/examples/codegate_2017-angrybird/
(angr) angr@508780408adf:~/angr-dev/angr-doc/examples/codegate_2017-angrybird$ ./solve.py
Im_so_cute&pretty_:)@@@
```

**Comment by rhelmot** [comment]
`./setup.sh -p angr-pypy` if I recall correctly

**Comment by Manouchehri** [comment]
Yep, thanks. Off-topic, but is there a reason why cpython is used for CI and Docker? I thought

**Comment by zardus** [comment]
The general plan we were following at some point is cpython as a default, with pypy for things that don't run in cpything (like colorguard). At the time, most people were still using cpython, but as we've been pushing people to use pypy, I could see switching tests to that. Ideally, angr would work well in both, though.

**Comment by Manouchehri** [comment]
I looked at this for a few minutes and gave up. Because the binary cannot even run on a _normal_ system without patching, I'm fine with it being a bit buggy in angr.

Suggesting this ticket be closed and a new one opened for the CPython vs. PyPy behavior in general.

**Comment by rhelmot** [comment]
I suggest you submit examples in the future in which you actually know how they work instead of _starting in the middle of main with an uninitialized rbp_ and invoking some sort of miracle to make them function.

**Comment by Manouchehri** [comment]
I stopped submitting examples awhile ago for that reason. Last one was
months ago.
