### ISSUE TITLE
Tried to follow the fauxware example in the documentation. Attribute errors, no SimFile, no stdin. 

### ISSUE THREAD

**Issue by swonlek** [angr/angr-doc#189]
when trying out the fauxware example from the documentation, there was this line
`state = p.factory.entry_state(stdin=angr.SimFile)`
 which i was running in ipython in the console, on Ubuntu. It gave me this error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-8-e7f2f77c150d> in <module>()
----> 1 state = p.factory.entry_state(stdin=angr.SimFile)

AttributeError: 'module' object has no attribute 'SimFile'
```
I am wondering if there is something missing in my installation process? I've also had problems with the later lines, where the console/ipython does not have stdin? 
```In [6]: sm = p.factory.simulation_manager()

In [7]: while True:
   ...:     s = state.step()
   ...:     if len(s.successors) == 2:
   ...:         break
   ...:     state = s.successors[0]
   ...:     

In [8]: state1, state2 = s.successors

In [9]: state1
Out[9]: <SimState @ 0x400692>

In [10]: state2
Out[10]: <SimState @ 0x400699>

In [11]: input_data = state1.posix.stdin.load(0,state.posix.stdin.size)
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-11-a4160580d1ed> in <module>()
----> 1 input_data = state1.posix.stdin.load(0,state.posix.stdin.size)

AttributeError: 'SimStateSystem' object has no attribute 'stdin'
```
Sorry I'm pretty new at all these things (and also new to Ubuntu), do let me know if this is likely due to incomplete installation or if i need to reconfigure some things. Thank you for your help!!

**Comment by rhelmot** [comment]
The docs target the version of angr installable from github, not pypi. The version on pypi is behind by a few months and doesn't have the refactor that added those elements.

I'd link you to an older version of the docs but previously the docs didn't have information about how to work with simfiles there... Look through the history of some of the examples I guess?

**Comment by swonlek** [comment]
does that mean i should not use `pip install angr` and instead install all the repos of claripy, archinfo, pyvex etc directly from github?

**Comment by zardus** [comment]
Please use the docker container (docker run -it angr/angr) or check out the
Dockerfile that defines it (in github.com/angr/angr-doc) for how it is
built. That'll be the most definite answer!

**Comment by rhelmot** [comment]
Yan that’s not the issue

You can use pip install angr. That’ll give you a totally functional installation. The problem is just that the docs are out of sync. To sync the docs back up you can look through the commit history from this repository, and check out the commit from the date listed on pypi. This will include examples of how to do the thing you want to do.
