### ISSUE TITLE
 which version of the angr source this document corresponds to?

### ISSUE THREAD

**Issue by Youlor** [angr/angr-doc#194]
Hello!
    I'm learning angr with document at `https://docs.angr.io/docs/states.html`. Now, I can't do this example with my version of the angr: 7.8.2.21(I installed by windows-install/install_angr.bat **today**). And the version of angr from pip can't do either.

My Enviroment: `Windows 10`

```
>>> simfile = angr.SimFile('myconcretefile', content='hello world!\n')
>>> simfile.set_state(state)
>>> data, actual_size, new_pos = simfile.read(0, 5)
```
**error1**:
When I use `simfile = angr.storage.file.SimFile('test', 'rw') `
Cause:
```
  File "G:/python/AngrTest/CoreTest.py", line 14, in <module>
    simfile = angr.storage.file.SimFile('test', content="123")
TypeError: __init__() takes at least 3 arguments (3 given)
```
**error2**:
When I use 
```
simfile = angr.storage.file.SimFile('test', 'rw', content="123")
simfile.set_state(state1)
data, actual_size, new_pos = simfile.read(0, 5)
```
Cause:
```
Traceback (most recent call last):
  File "G:/python/AngrTest/CoreTest.py", line 15, in <module>
    simfile.set_state(state1)
  File "C:\python27-x64\lib\site-packages\angr\storage\file.py", line 86, in set_state
    self.content.set_state(st)
AttributeError: 'str' object has no attribute 'set_state'
```

**error3**:
When I use
```
simfile = angr.storage.file.SimFile('test', 'rw')
simfile.set_state(state1)
data, actual_size, new_pos = simfile.read(0, 5)
```
Cause:
```
Traceback (most recent call last):
  File "G:/python/AngrTest/CoreTest.py", line 17, in <module>
    data, actual_size, new_pos = simfile.read(0, 5)
TypeError: 'int' object is not iterable
```
So, How Can I learn angr correct?
Thanks!

**Comment by rhelmot** [comment]
The docs correspond to the tip-of-tree development version of angr, which you seem to have. I have no idea why you pointed at that page in the docs, which does not include _anything_ like `SimFile('test', 'rw')`, and then wrote that code.

We run the code samples in the docs against the current angr on every push as part of CI, so they definitely work.

**Comment by Youlor** [comment]
Thanks! I maybe not uninstall angr from pip totally, so the newest python code don't copy.
