### ISSUE TITLE
The question about using LibVEX’optimization

### ISSUE THREAD

**Issue by taozi-xx** [angr/angr-doc#231]
When I use angr's pyvex with vex optimizations enabled to lift the binary to Vex IR, I found when I set the optimization option to 2，the generated vex IR is same as the generated vex IR that the optimization option is 1.
What can cause this problem?

**Comment by ltfish** [comment]
I vaguely remember that level 2 is level 1 + loop unrolling. If you don’t have loops in your basic block, they can yield the same result.

**Comment by taozi-xx** [comment]
@Itfish 
But I think there should be no loop structure in the basic block. Because the loop structure should have a jump statement，there should be no jump statement in the basic block.

**Comment by rhelmot** [comment]
Correct. afaik it affects things deeper in libvex when it is used for JIT reassembly as well.

**Comment by taozi-xx** [comment]
@rhelmot
Sorry, I didn't understand what you mean.

**Comment by rhelmot** [comment]
angr only uses half of libvex. its intended usage, the way valgrind uses it, is to lift blocks into IR, instrument them, and then just-in-time reassemble them into instrumented native code to be executed. opt level 2 effects loop unrolling in these later stages.

**Comment by ltfish** [comment]
> But I think there should be no loop structure in the basic block.

For example, `rep` prefixes on x86.

**Comment by taozi-xx** [comment]
@rhelmot
Thank you for your explanation. Now I understand.

**Comment by taozi-xx** [comment]
@Itfish
I get it. Thank you for your reply.
