### ISSUE TITLE
The question about what can angr do

### ISSUE THREAD

**Issue by taozi-xx** [angr/angr-doc#234]
I read an Chinese Blog that said Angr can translate translate IR into expression which  focus on the IR semantics . But I haven't found any functions in Angr related to it.

**Comment by rhelmot** [comment]
`project.factory.block(address).vex`, which is a shortcut for `pyvex.lift(bytes, address, arch)`, returns a VEX block, an intermediate representation which specifeis the exact semantics of a block of code. Documentation for it can be found here: https://docs.angr.io/advanced-topics/ir

**Comment by taozi-xx** [comment]
@rhelmot 
I know that Angr can translate a binary into an intermediate representation (IR)， I wonder after getting the IR， if Angr can  translate IR into expression further.

**Comment by ltfish** [comment]
Can you post the URL to the Chinese blog? Maybe it’s some sort of misunderstanding. It might be talking about claripy ASTs.

**Comment by taozi-xx** [comment]
https://blog.csdn.net/nku____/article/details/78538602 
This is the URL to the Chinese blog.

**Comment by ltfish** [comment]
Thanks. It does not talk about AIL at all. At the moment AIL is mostly used for decompilation.
