### ISSUE TITLE
The question about VEX in angr

### ISSUE THREAD

**Issue by taozi-xx** [angr/angr-doc#243]
When I use the 
“irsb = proj.factory.block(proj.entry).vex
 irsb.pp()”
to print the VEX of the basic block, I found a problem that， in some cases， the output results is different from the result using angr-utils to visualisation for CFG.

For example,
for a same basic block, the output under the first method is：
  00 | ------ IMark(0x405d8a, 7, 0) ------
   01 | ------ IMark(0x405d91, 4, 0) ------
   02 | PUT(rdx) = 0x0000000000611778
   03 | PUT(rip) = 0x0000000000405d95

the output under the second method is：（The results I observed from the visualized CFG）
 00 | ------ IMark(0x405d8a, 7, 0) ------
 01 |  PUT(rax) = 0x0000000000611800
   02 | ------ IMark(0x405d91, 4, 0) ------
   03 | PUT(rdx) = 0x0000000000611778
   04 | PUT(rip) = 0x0000000000405d95

The assembly instructions of the basic block is ：
0x405d8a:	lea	rax, [rip + 0x20b96f]
0x405d91:	lea	rdx, [rax + 0x78]
The instruciton of  0x405d8a  in the first case， it dont has  corresponding intermediate representation， but in the second case， it has.

What can cause this problem?

**Comment by rhelmot** [comment]
Angr-utils is showing you the disassembly. This is different from the IR.
Notably, the IR you show has been optimized, which may cause some effects
to be omitted if they don't contribute to the overall effect of the *entire
block*

To not have this happen, use block(opt_level=0).

**Comment by taozi-xx** [comment]
I tried. But I found the result is:
00 | ------ IMark(0x405d8a, 7, 0) ------
   01 | t0 = Add64(0x0000000000405d91,0x000000000020b96f)
   02 | PUT(rax) = t0
   03 | PUT(rip) = 0x0000000000405d91
   04 | ------ IMark(0x405d91, 4, 0) ------
   05 | t10 = GET:I64(rax)
   06 | t9 = Add64(t10,0x0000000000000078)
   07 | t1 = t9
   08 | PUT(rdx) = t1
   09 | PUT(rip) = 0x0000000000405d95

**Comment by rhelmot** [comment]
That is the correct result. What are you expecting?

**Comment by taozi-xx** [comment]
I wonder if there is any way to get the same results as visualized CFG.

**Comment by rhelmot** [comment]
I have no idea what's going on. It looks like the first example has messed up the optimization somehow. Can you please post a reproducable testcase?

**Comment by rhelmot** [comment]
oh, maybe try `block(size=11)`? If the thing you pasted had more output that would have explained it.

**Comment by taozi-xx** [comment]
I got the same result. Thank you very much!

**Comment by taozi-xx** [comment]
Sorry， I have another question, . block(size=11), how to set the value of size  parameter ？

**Comment by rhelmot** [comment]
It is the size of the basic block. You can query it from the CFG node.

If you're trying to replicate angr-utils, you should look into the angr-utils source code.

**Comment by taozi-xx** [comment]
Thank you very much!

**Comment by axt** [comment]
Hi! angr-utils is using this method, to get the vex instructions, where size is coming from the CFG. 
```
 vex = self.project.factory.block(addr=addr, size=size).vex
```

**Comment by taozi-xx** [comment]
@axt 
But I dont know how to set the value of size parameter，I tried to set the size parameter to block.size, I
found the results were still different.  
vex = self.project.factory.block(addr=addr, size=block.size).vex
