### ISSUE TITLE
whitehat_crypto400 example does not find FLAG

### ISSUE THREAD

**Issue by hidde-jan** [angr/angr-doc#244]
It seems `solve.py` is no longer able to find the FLAG. It seems `b"FLAG IS"` is never included in stdout anymore.

I ran the example in an angr/angr docker container with angr version angr==8.18.10.25

The output of stdout is always `b'INPUT OK\nINPUT IS NOT GOOD ENOUGH.\n'`

**Comment by twizmwazin** [comment]
Can you double check if this is still an issue? Just pulled everything and tested locally, everything seems to be working as expected on my end.

**Comment by hidde-jan** [comment]
No luck. I've checked with the following steps:

1. Pull angr/angr:latest docker image
2. run ./git_all.sh pull
3. run pip install -e ./pyvex && pip install -e ./angr
4. run python solve.py in example dir with angr virtualenv

Final output:
```
INFO    | 2019-03-21 10:25:20,218 | angr.sim_manager | Stepping active of <SimulationManager with 1 active, 6 avoid>
INFO    | 2019-03-21 10:25:20,226 | angr.sim_manager | Stepping active of <SimulationManager with 1 active, 6 avoid>
[*] example guess: b'nyJo-TBU'
[*] brute-forcing 6392 possibilities
6392 100% |#########################################################################################################################| Time: 0:00:27
None
```

Pip freeze:
```
-e git+https://github.com/angr/ailment@c9c64944f8d28374e798d38d25c2f77bb95db130#egg=ailment
alabaster==0.7.12
ana==0.5
-e git+https://github.com/angr/angr@ad08c21a53f99fe0237ea9c29c736fa9dc8a3c64#egg=angr
-e git+https://git:@github.com/salls/angrop@91ae29f52465b3c4bf82deb41fe24dfc89dc9a4f#egg=angrop
-e git+https://github.com/angr/archinfo@2503dc1a91e66e7ee7a14b7ff5cf88463ee0c2d7#egg=archinfo
asn1crypto==0.24.0
astroid==2.2.5
Babel==2.6.0
backcall==0.1.0
bitstring==3.1.5
cachetools==3.1.0
capstone==4.0.1
certifi==2019.3.9
cffi==1.12.2
chardet==3.0.4
-e git+https://github.com/angr/claripy@f00f4f82ce35f433ecb2ce0e1da2fc9069f33294#egg=claripy
-e git+https://github.com/angr/cle@3701084e36aa0d7307be2d490d1ac4cdfae64594#egg=cle
commonmark==0.8.1
-e git+https://git:@github.com/zardus/cooldict@e85d9db0c0b05e95dd3bb7c1c61d24ff78167c57#egg=cooldict
coverage==4.5.3
cryptography==2.6.1
cvc4-solver==1.6
decorator==4.4.0
docutils==0.14
dpkt==1.9.2
flaky==3.5.3
future==0.17.1
gitdb2==2.0.5
GitPython==2.1.11
-e git+https://git:@github.com/zardus/idalink@cf68144e7c72679a5429d8b8d9e9aa316d9b79ac#egg=idalink
idna==2.8
imagesize==1.1.0
ipdb==0.11
ipython==7.3.0
ipython-genutils==0.2.0
isort==4.3.15
itanium-demangler==1.0
jedi==0.13.3
Jinja2==2.10
keystone-engine==0.9.1.post3
lazy-object-proxy==1.3.1
MarkupSafe==1.1.1
mccabe==0.6.1
-e git+https://git:@github.com/rhelmot/monkeyhex@61a585c5a6adcb013ce5abe9127041954942faef#egg=monkeyhex
-e git+https://git:@github.com/zardus/mulpyplexer@98515f1a587bc62693b6b33c730f0525ed9b85a8#egg=mulpyplexer
networkx==2.2
nose==1.3.7
nose-timer==0.7.5
packaging==19.0
parso==0.3.4
pefile==2018.8.8
pexpect==4.6.0
pickleshare==0.7.5
pkg-resources==0.0.0
plumbum==1.6.7
progressbar==2.5
prompt-toolkit==2.0.9
psutil==5.6.1
ptyprocess==0.6.0
pycparser==2.19
pyelftools==0.25
Pygments==2.3.1
pylint==2.3.1
pyOpenSSL==19.0.0
pyparsing==2.3.1
PySMT==0.8.0.post1
-e git+https://github.com/angr/pysoot@9b42de99174b31db8964d3ce3f902fe61a2f0773#egg=pysoot
pytz==2018.9
-e git+https://github.com/angr/pyvex@7c41d46fe40d86f51f89c4e34f049f7097af4f0b#egg=pyvex
recommonmark==0.5.0
requests==2.21.0
rpyc==4.0.2
six==1.12.0
smmap2==2.0.5
snowballstemmer==1.2.1
sortedcontainers==2.1.0
Sphinx==1.8.5
sphinx-rtd-theme==0.4.3
sphinxcontrib-websupport==1.1.0
-e git+https://git:@github.com/rhelmot/superstruct@be1d1c402cc9b6b0a94b458862e40a55efc445d0#egg=superstruct
traitlets==4.3.2
typed-ast==1.3.1
unicorn==1.0.2
urllib3==1.24.1
wcwidth==0.1.7
wrapt==1.11.1
z3-solver==4.5.1.0.post2
```

**Comment by twizmwazin** [comment]
Excellent, just did some testing myself. As before, it "works on my machine," which happens to be Fedora 29. But literally no where else. I built a new docker image, I modified the docker image to use F29 as a base in case maybe Ubuntu has a buggy library, but then it turns out it doesn't work there either. My next best guess is there is an optional dependency somewhere that is screwing with things, and I just happened to have it installed. Time to dig.

**Comment by twizmwazin** [comment]
Ok, so I've done some further testing and found that my previous estimate was pretty wrong. The binary is statically linked, so its definitely not a library issue. Running natively on my machine it still produces the flag when running `./whitehat_crypto400 nytEaTBU`, both inside angr and standalone. Running the binary through any of ltrace, strace, and gdb cause a failure, as does running it inside of docker. My next guess is perhaps there is some sort of timing, though I'm not terribly sure there. What I do think though is that this doesn't seem like an issue with angr itself, but possibly weird conditions for the challenge that aren't documented.

**Comment by rhelmot** [comment]
It's an anti-debugging feature of the binary where it will not run if it cannot ptrace itself. It cannot work inside docker unless you have enabled ptrace inside the docker.
