### ISSUE TITLE
How to use solve.py with the fauxware binary example

### ISSUE THREAD

**Issue by sylhare** [angr/angr-doc#248]
Hi,

I have been successfully running the `solve.py` of the fauxware example, seeing the `SOSNEAKY` string. However I am puzzled with the last instruction:

```python
# You should be able to run this script and pipe its output to fauxware and fauxware will authenticate you.
```

I have tried:
```bash
python solve.py | ./fauxware
./fauxware | python solve.py
```

But I still get a `permission denied`. I think I might be missing out on something simple. I am relatively new to all this so I might have overseen something basic.

Thanks in advance

**Comment by rhelmot** [comment]
fauxware outputs `Go Away!` when there is bad input, not `permission denied`. did you somehow chmod -x fauxware?

this is what it looks like for me:

```
[+] ~/angr/angr-doc/examples/fauxware% python solve.py | ./fauxware
Username: 
[[ a bunch of warnings ]]
Password: 
Welcome to the admin console, trusted user!
```

**Comment by sylhare** [comment]
Ahah, yes indeed! 🤦‍♂️ 

However then I had an error:
```
-bash: ./fauxware: cannot execute binary file
```
I realized, while recompiling the source code.
```
gcc -o fauxware fauxware.c
```
It seems that on line 29th (in the `accepted()` function), I had a warning:
```bash
fauxware.c:29:1: warning: control reaches end of non-void function [-Wreturn-type]
```
So I added a `return 0;` and could compile it then make it executable `chmod +x fauxware`.
And then it worked perfectly thanks to your explanation.

Thanks a lot! 😉
