### ISSUE TITLE
How to run symbolic execution in a subfunction?

### ISSUE THREAD

**Issue by tomoarrow** [angr/angr-doc#272]
hi, I'm a beginner in symbolic execution. When reading this doc, I noticed many examples start symbolic execution at entry_state(). But binary files in real world are always very large. I think running from beginning of a binary file is not practical. So I wonder if symbolic execution could work on large files. I tried to run symbolic execution in a subfunction but failed.

**Comment by rhelmot** [comment]
Here's the part of the docs you're looking for: https://docs.angr.io/core-concepts/states#state-presets

You don't have to use `entry_state`, you can use `call_state` to start at the beginning of a function or `blank_state` to start wherever you want.

**Comment by tomoarrow** [comment]
> Here's the part of the docs you're looking for: https://docs.angr.io/core-concepts/states#state-presets
> 
> You don't have to use `entry_state`, you can use `call_state` to start at the beginning of a function or `blank_state` to start wherever you want.

Should I initialize mem and regs first? When running symbolic execution，the output is always “Filling memory at xxxx with 4 unconstrained bytes referenced from xxxx”. I think it's a state space explosion problem. But I don't know what their values should be set to.

**Comment by rhelmot** [comment]
That output is just a warning message. Execution is still proceeding and you can evaluate in other ways whether it is "working". You should initialize memory and registers to whatever extent you know the values should be, and then any unknown values can be automatically filled with symbolic values as per the warning message, so angr will explore the state space of what could happen given any values of it.

**Comment by tomoarrow** [comment]
> That output is just a warning message. Execution is still proceeding and you can evaluate in other ways whether it is "working". You should initialize memory and registers to whatever extent you know the values should be, and then any unknown values can be automatically filled with symbolic values as per the warning message, so angr will explore the state space of what could happen given any values of it.

when I run `simgr.explore()`, memory usage increases too fast. My computer is down after a few hours. Could you explain why it occupies so much memory and how to solve this problem?

**Comment by tomoarrow** [comment]
> That output is just a warning message. Execution is still proceeding and you can evaluate in other ways whether it is "working". You should initialize memory and registers to whatever extent you know the values should be, and then any unknown values can be automatically filled with symbolic values as per the warning message, so angr will explore the state space of what could happen given any values of it.

When I use blank_state() without initialization, the program quickly stop with some unconstrained state.  Is there a general initialization method for any binary file？I didn't find in the doc.

**Comment by rhelmot** [comment]
The only general initialization method is to start from the entry point. You have to do everything yourself if you're starting from some middle point. angr is designed to help you with that process by showing the aforementioned warning messages to help you pin down the relevant uninitialized parts.

**Comment by ltfish** [comment]
> Is there a general initialization method for any binary file?

Under-constrained symbolic execution may help with that. There is an implementation inside angr (see state option `UNDER_CONSTRAINED_SYMEXEC`).

**Comment by tomoarrow** [comment]
Sorry, after adding `UNDER_CONSTRAINED_SYMEXEC` option, I got a TypeError:
```
~/anaconda3/lib/python3.6/site-packages/angr/state_plugins/uc_manager.py in assign(self, dst_addr_ast)
     39         """
     40 
---> 41         if dst_addr_ast.uc_alloc_depth > self._max_alloc_depth:
     42             raise SimUCManagerAllocationError('Current allocation depth %d is greater than the cap (%d)' % \
     43                 (dst_addr_ast.uc_alloc_depth, self._max_alloc_depth))

TypeError: '>' not supported between instances of 'NoneType' and 'int'
```
And I don't understand why symbolic executor cannot work with unconstrained state. Could you explain it?

**Comment by rhelmot** [comment]
idk why fish keeps recommending underconstrained symbolic execution to people

Symbolic execution is a powerful but expensive technique. Modeling the full extent of possibilities for a state to touch is extremely expensive in both time and memory. When you start with too much data unconstrained, there's no way of knowing what will happen, and angr will do one of three things: 1) concretize the data and move on, 2) try to model all the possibilities precisely (expensive), or 3) give up and tell you there's a problem. "unconstrained" states are the third one, because the instruction pointer has become unconstrained and that literally could result in absolutely anything.

"Why symbolic executors cannot work with unconstrained state" is a question that you should answer by reading the past decade of computer security literature on the subject.
