### ISSUE TITLE
Link to orgy.md is broken

### ISSUE THREAD

**Issue by gitttt** [angr/angr-doc#29]
The link in the readme to orgy.md is broken. Is the orgy component even in the repo?
If not, how would you suggest to do distributed analysis with angr?

**Comment by ltfish** [comment]
This is a @zardus question :-)

**Comment by zardus** [comment]
Yeah, that stuff is way obsolete. Our current multi-processor analysis has been swallowed up in our CGC work, and we don't have a good replacement... Personally, I would recommend using rpyc (https://rpyc.readthedocs.org/en/latest/) with some sort of pool of client workers, but we don't have anything out-of-the-box at the moment...

That being said, having something that can run analyses on multiple hosts, *transparently* (maybe with a mulpyplexer frontend!) would be awesome!

**Comment by gitttt** [comment]
Thanks for the info!
