### ISSUE TITLE
How to symbolicly execute a program with glibc-2.27？

### ISSUE THREAD

**Issue by liwl23** [angr/angr-doc#290]
Hi I‘m a newbie to symbolic execution. And I am trying to use angr to run a program under libc-2.27. But when I try to run the program under angr, the program will call a null function pointer and crash. 
The code of my program is as follows,
```C
#include “stdio”
int main(){
     malloc(10);
}
```
The compile command is 
```sh
gcc -O0 test.c -o test
```
and the python code is
```python
import angr
p = angr.Project(‘./test’,use_sim_procedures=False)
smgr = p.factory.state_manager(p.factory.entry_state())
smgr.explore(find=[xxx])#xxx is the address of the next instruction of "call malloc"
```
I traced the execution #under angr, and found that the malloc fuction will try to call a global function pointer in ld.so. The function pointer is null when runing under angr, but is a legal address when runing normally. I guess that the ld.so will initialize these function pointer when it loads libraries, but angr doesn't do these initialization.Does anyone  know how solve this problem?

**Comment by rhelmot** [comment]
In order to run all the initializers necessary to do intensive runs through libc code, you need to use `full_init_state` instead of `entry_state`. The former will run all the initializers and then drop you at the program entry point, while the latter will just drop you off at the entry point.
