### ISSUE TITLE
simgr does not find all active state

### ISSUE THREAD

**Issue by blbi** [angr/angr-doc#299]
Hi, I'm using angr to explore a mozjpeg binary.
The binary gets input like `mozjpeg blah.bmp <int value between 10-100>`
So i set the argument like this
```python
sym_arg = claripy.BVS("sym_arg", 8*11)
symbit = sym_arg.chop(8)

argv = [proj.filename, sym_arg]
state = proj.factory.blank_state(addr=main_addr, args=argv)

for i, c in enumerate('test.bmp '):
	state.add_constraints(symbit[i] == c)
```
and there is a 'test.bmp' file in same directory
but if i explore to find specific position in main function, it didn't return any result and just show 
_list index out of range error_ at _simgr.found[0]_

so i analyze by `step()` and find out  it didn't find all state
below shows part of main
```
0x000055555555b2da <+94>:	call   0x555555555f60 <tjGetScalingFactors@plt>
0x000055555555b2df <+99>:	mov    QWORD PTR [rip+0x20407a],rax        # 0x55555575f360 <scalingFactors>
0x000055555555b2e6 <+106>:	mov    rax,QWORD PTR [rip+0x204073]        # 0x55555575f360 <scalingFactors>
0x000055555555b2ed <+113>:	test   rax,rax
0x000055555555b2f0 <+116>:	je     0x55555555b2fc <main+128>
0x000055555555b2f2 <+118>:	mov    eax,DWORD PTR [rip+0x204070]        # 0x55555575f368 <nsf>
0x000055555555b2f8 <+124>:	test   eax,eax
0x000055555555b2fa <+126>:	jne    0x55555555b32d <main+177>
0x000055555555b2fc <+128>:	call   0x555555555d00 <tjGetErrorStr@plt>
0x000055555555b301 <+133>:	mov    rcx,rax
```
at <main+99> simgr make 2 active state <main+118> and <main+128>
<main+128> is the point that make the program finish so i want to go <main+177>
**but at <main+118>, if i execute `step()`, simgr didn't consider <main+177> state but only show <main+128> as active state**
the warning log shows `Exit state has over 256 possible solutions. Likely unconstrained; skipping. <BV64 mem_7ffffffffff0000_52_64{UNINITIALIZED}>`
(the eax value is the return value of _tjGetScalingFactors_ function at <main+94>)
i think even if the eax is symbolic value, <main+177> state can be considered with the eax value that is not zero
but simgr considered the eax value as only 0
what's the problem???

**Comment by rhelmot** [comment]
1) it's impossible to tell what's going on unless you give us the exact reproduction instructions, including the full test script and binary
2) If you expect the program to be able to interact with programs on your filesystem, you should pass `concrete_fs=True` to the state. If you expect the state to think it is in your current working directory, you should pass `cwd=<current cwd>` as well.
3) The eax value is _not_ the return value of `tjGetScalingFactors`, it is the value of the global variable `nsf`, which is not touched in the snippet you've posted. If this variable is part of the bss and is never initialized, its default value will be zero.

**Comment by blbi** [comment]
Thanks for the answer.
i'm having a hard time with angr
i want to use my file as concrete value 
below is my full script 
```python
import angr
import claripy

proj = angr.Project('tjbench', load_options={'auto_load_libs':False})

main_addr = 0x40727c
find_addr = 0x408162

sym_arg = claripy.BVS("sym_arg", 8*11)
symbit = sym_arg.chop(8)
argv = [proj.filename, sym_arg]

file = open('test.bmp','rb')
simfile = angr.SimFile('simfile', content=file.read())
files = {'simfile':simfile}
#state = proj.factory.blank_state(addr=main_addr, args=argv, concrete_fs=True, fs=files)
#this makes error. I don't know why
#WARNING | 2020-01-28 22:46:24,161 | [37mangr.sim_state[0m | [37mUnused keyword arguments passed to SimState: args[0m
#Traceback (most recent call last):
#  File "<stdin>", line 1, in <module>
#  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\site-packages\angr\factory.py", line 71, in blank_state
#    return self.project.simos.state_blank(**kwargs)
#  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\site-packages\angr\simos\linux.py", line 189, in state_blank
#    state.register_plugin('fs', SimFilesystem(files=fs, pathsep=pathsep, cwd=cwd, mountpoints=mounts))
#  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\site-packages\angr\state_plugins\filesystem.py", line 43, in __init__
#    self.insert(fname, files[fname])
#  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\site-packages\angr\state_plugins\filesystem.py", line 179, in insert
#    return mountpoint.insert(chunks, simfile)
#  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\site-packages\angr\state_plugins\filesystem.py", line 307, in insert
#    simfile.set_state(self.state)
#  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\site-packages\angr\storage\file.py", line 202, in set_state
#    super(SimFile, self).set_state(state)
#  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\site-packages\angr\state_plugins\symbolic_memory.py", line 233, in set_state
#    super(SimSymbolicMemory, self).set_state(state)
#  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\site-packages\angr\storage\memory.py", line 347, in set_state
#    SimStatePlugin.set_state(self, state)
#  File "C:\Users\usr\AppData\Local\Programs\Python\Python37\lib\site-packages\angr\state_plugins\plugin.py", line 24, in set_state
#    self.state = state._get_weakref()
#AttributeError: 'NoneType' object has no attribute '_get_weakref'

state = proj.factory.blank_state(addr=main_addr, args=argv,fs=files)

for i, c in enumerate('test.bmp '):
	state.add_constraints(symbit[i] == c)

simgr = proj.factory.simulation_manager(state)
simgr = simgr.explore(find = find_addr, enable_veritesting=True)
f = simgr.found[0]
```

And i checked using `step()` instead of `explore()`
```
>>> simgr = proj.factory.simulation_manager(state)
>>> simgr.step()
WARNING | 2020-01-28 23:02:57,993 | [32mangr.state_plugins.symbolic_memory[0m | [32mFilling register rbp with 8 unconstrained bytes referenced from 0x40727c (main+0x0 in tjbench (0x727c))[0m
WARNING | 2020-01-28 23:02:57,999 | [32mangr.state_plugins.symbolic_memory[0m | [32mFilling register rdi with 8 unconstrained bytes referenced from 0x407284 (main+0x8 in tjbench (0x7284))[0m
WARNING | 2020-01-28 23:02:58,001 | [32mangr.state_plugins.symbolic_memory[0m | [32mFilling register rsi with 8 unconstrained bytes referenced from 0x407287 (main+0xb in tjbench (0x7287))[0m
<SimulationManager with 1 active>
>>> simgr.active
[<SimState @ 0x401f60>]
>>> simgr.step()
<SimulationManager with 1 active>
>>> simgr.active
[<SimState @ 0x1000148>]
>>> simgr.step()
<SimulationManager with 1 active>
>>> simgr.active
[<SimState @ 0x4072df>]
>>> simgr.step()
<SimulationManager with 2 active>
>>> simgr.active
[<SimState @ 0x4072fc>, <SimState @ 0x4072f2>]
>>> simgr.step()
<SimulationManager with 2 active>
>>> simgr.active
[<SimState @ 0x401d00>, <SimState @ 0x4072fc>]
```
<SimState @ 0x4072f2> is <main+118>
i don't know why <SimState @ 0x4072f2> don't go to <main+177> that position mentioned at first comment
i checked it can reach to that position with the test file with specific input _(tjbench test.bmp 90)_

and the eax  is the value of `nsf` but before the test(<main+124>), the program store the return value of `tjGetScalingFactors` function at `nsf` global variable


This is the target binary [tjbench.zip](https://github.com/angr/angr-doc/files/4122802/tjbench.zip)
and this is my test file [test.zip](https://github.com/angr/angr-doc/files/4122832/test.zip)

**Comment by rhelmot** [comment]
The traceback is caused by providing both `concrete_fs` and `fs`. The former is supposed to import your entire host filesystem to the guest, and the latter is supposed to provide an explicit guest filesystem. I can add a commit to give you a better error message.

> and the eax is the value of nsf but before the test(<main+124>), the program store the return value of tjGetScalingFactors function at nsf global variable

It really doesn't. It passes the address of `nsf` as an outparam to `tjGetScalingFactors`, which I'm guessing is imported from libturbojpeg. If angr hasn't loaded the binary's dynamic dependencies, which it necessarily will not because you specified `auto_load_libs=False`, then angr has no way of knowing that anything should be stored at that address. angr's behavior in modeling an unknown function is to provide a symbolic variable in the return value register, but it can't tell that the argument is supposed to be an outparam.
