### ISSUE TITLE
symbolic_variable bp can't be triggered with BP_BEFORE

### ISSUE THREAD

**Issue by uriyay** [angr/angr-doc#310]
This [simulation.md](https://github.com/angr/angr-doc/blob/master/docs/simulation.md) says that `symbolic_variable` BP can be triggered with BP_BEFORE, but I saw in the recent version of angr that is not the situation. There is only one place where `symbolic_variable` is triggered, and that's in [solver.py](https://github.com/angr/angr/blob/454ce43bf5af81e07cb6d2a68e089c5de3e7681e/angr/state_plugins/solver.py#L384)

**Comment by rhelmot** [comment]
fixed. thanks!
