### ISSUE TITLE
Missing link for examples.md??

### ISSUE THREAD

**Issue by tlabruyere** [angr/angr-doc#323]
I was looking at the page https://github.com/angr/angr-doc/blob/master/docs/examples.md#cgc-crash-identification and could not find the angr script that was associated with heading "CGC crash identification". Is there supposed to be one there?

**Comment by antoniobianchi333** [comment]
I think you are referring to this:
https://github.com/angr/angr-doc/tree/master/examples/CADET_00001

**Comment by tlabruyere** [comment]
Yes, that is it. I could not find that link in that page. Should that link be added to the page? Would you like a PR for this?

**Comment by antoniobianchi333** [comment]
Can you submit a PR adding the link?
thanks

**Comment by tlabruyere** [comment]
Will do, thanks
