### ISSUE TITLE
Type hints VS Docstring

### ISSUE THREAD

**Issue by Pamplemousse** [angr/angr-doc#325]
### The good

Recently, an effort has been made to bring [type hints](https://www.python.org/dev/peps/pep-0484/) into the `angr` codebase.

Not only it provides a safety net to check the consistency of data structures as they will be moved along at runtime, but it also provides good information about such structure for developers, easing reading the code and contributing.

In that sense, good type hints are a form of documentation.

### The bad

However, I noted two things about the use of both "type hints" and "docstrings":
  * They induce a certain form of redundancy of information;
  * They might even introduce certain discrepancies, say if a type hint is changed after a refactoring, but the relevant docstrings are not updated (note that this problem IS already present).

### The solution? (IMHO)

Type hints are more pertinent than docstring:
  * They can be statically verified;
  * IDEs can make use of them to help developers.

So, my proposal would be to **always favor type hints over docstrings**.
But that raises the need for [the angr API documentation](https://angr.io/api-doc/angr.html) to make use of those type hints.
[sphinx-autodoc-typehints](https://github.com/agronholm/sphinx-autodoc-typehints) is probably something to look at...

**Comment by ltfish** [comment]
Totally forget about sphinx... I agree that when type hints are available, we should remove the types in docstrings.
