### ISSUE TITLE
Remove references to Layer7 and other Surveyor solves

### ISSUE THREAD

**Issue by mubix** [angr/angr-doc#368]
Because of this commit: efce300efe79ba2d6c5259d42ae66ee89757e931
This example: https://github.com/angr/angr-doc/blob/master/docs/more-examples.md#crackme-example-layer7-ctf-2015---windows-challenge-onlyone

Should be removed and any others like it. Or a new solve should be uploaded for the binary? :)

**Comment by rhelmot** [comment]
fixed in ede1fb4. thanks!
