### ISSUE TITLE
Help on CFG

### ISSUE THREAD

**Issue by hanchaoqiang** [angr/angr-doc#38]
i'm newer,i need you help  my cfg can't output graph  and  i don't kown how to load a *bin  as a project,thanks

**Comment by ltfish** [comment]
Can you please elaborate your question?

And feel free to use Chinese if you are more comfortable with it :-)

**Comment by zardus** [comment]
In general, tips on how to get started are here: https://github.com/angr/angr-doc/blob/master/docs/toplevel.md

**Comment by hanchaoqiang** [comment]
我的CFG可以加载工程也能输出节点和边但就是不能输出流图，我是在做一个漏洞发现的工作，这是我的毕业课题

**Comment by hanchaoqiang** [comment]
my cfg can load a project and output the nodes and nodes,but it can't output the graph.

**Comment by ltfish** [comment]
请问什么叫做“流图”？

**Comment by ltfish** [comment]
这里有一些中文的 angr 教程，或许对你有帮助：http://ysc21.github.io/

**Comment by hanchaoqiang** [comment]
非常感谢您的解答和帮助

**Comment by ltfish** [comment]
不用谢。如果你的问题没有解决的话，可以重新打开这个问题。
