### ISSUE TITLE
where can i find the source code of the folder "example"?

### ISSUE THREAD

**Issue by bboysteed** [angr/angr-doc#383]
because the example folder's codes are build for amd64 linux,which i can't run in macOS,if i can get the source code, i can build for myself,and just run to look at what the binary used for,and get some info to analyse.

**Comment by twizmwazin** [comment]
In general most of the examples are originally from CTF competitions where source code was not provided. You may be able to find source for some of them online or by contacting the original authors. However, recompiling may not produce a binary compatible with the corresponding solve.py script. I would strongly suggest using a VM to run the binaries instead.
