### ISSUE TITLE
cfg

### ISSUE THREAD

**Issue by hanchaoqiang** [angr/angr-doc#41]
ERROR   | 2016-04-06 23:40:03,206 | angr.analyses.cfg | Caught an AngrError during CFG recovery at 0x40b768 (.text)
raise PyVEXError(ffi.string(pvc.last_error) if pvc.last_error != ffi.NULL else "unknown error")
angr.errors.AngrTranslationError: ('Translation error', <class 'pyvex.PyVEXError'>, PyVEXError('exception in VEX (see console)',))
I can print the CFG of examples in the github  ,but when i load a binnary myself(DLink's webs) ,it is error

**Comment by rhelmot** [comment]
This is expected. 

What you've pasted there is not an actual error, it is logging output of angr's CFG analysis catching an internal error and continuing. If you let the analysis continue, it should produce a result. 

@ltfish you should really not output logging errors unless you want bug reports submitted when they pop up, I guess the moral of the story is!

**Comment by hanchaoqiang** [comment]
what  should i do to let the analysis cotinue and produce a result ,where can i find a example for binanry disassembly and procedure abstraction..
thank you

**Comment by rhelmot** [comment]
That line being printed to your screen does not mean that analysis has been terminated. It should still be running, and eventually the function you called (`project.analysis.CFG()`) will return.

If you have more questions you should ask the #angr IRC channel, on the IRC server irc.freenode.net.

**Comment by ltfish** [comment]
Please open an issue in the angr repo if your issue is angr-related, not angr-doc specific. I'm closing this issue now.

**Comment by hanchaoqiang** [comment]
but when print cfg.graph.nodes() , it only print [],  the framwork can run well in the  IDApro,why?

**Comment by hanchaoqiang** [comment]
vex: priv/main_main.c:769 (LibVEX_Translate): Assertion `0 == sizeof(VexGuestMIPS32State) % LibVEX_GUEST_STATE_ALIGN' failed.
???

**Comment by ltfish** [comment]
angr-doc 只接受与文档相关的问题。关于 angr 的问题，请在 https://github.com/angr/angr 的 Issues 中提出，谢谢。
