### ISSUE TITLE
`test_examples.test_defcon2016quals_baby_re` is timing out in CI

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr-doc#419]

**Comment by rhelmot** [comment]
I believe the culprit is actually `test_examples.test_angrybird`. When I run it, it eats all my RAM and eventually gets OOM-killed. I would not be surprised if this mechanism was not working in the container.

**Comment by twizmwazin** [comment]
The z3 commit log is not helpful in debugging this, but it doesn't look like z3 has had a release since may 4th, so I'm not sure if that is the case. Glad it's at least not timing out now though.
