### ISSUE TITLE
Testing the java_androidnative1 example failed with error

### ISSUE THREAD

**Issue by GanbaruTobi** [angr/angr-doc#420]
After installing sdk and so on and running the solve.py, i get the error:

"angr.errors.AngrSimOSError: No JNI lib was loaded. Is the jni_libs_ld_path set correctly?"

When setting auto_load_libs to True this example works
https://github.com/angr/angr-doc/blob/8b415e9296296ce554dcfa27092ccea042edfbc4/examples/java_androidnative1/solve.py#L37

**Comment by twizmwazin** [comment]
If it works with auto_load_libs=True, then that is likely correct. Feel free to open a PR correcting it or I can do so this week.
