### ISSUE TITLE
Move API docs to project repos.

### ISSUE THREAD

**Issue by twizmwazin** [angr/angr-doc#421]
We should move the api docs to their own repos instead of this one. They don't really serve a purpose being here since each file is discrete to each repo. Additionally, it is very common case requiring PR syncing that can be avoided. This is also a step towards future decoupling of angr modules.

**Comment by twizmwazin** [comment]
So here's a plan that I think would work well, in two steps:

First step, start generating the docs with [pdoc3](https://github.com/pdoc3/pdoc). This tool will generate our documentation from the docstrings in each repo, so there is no need to do anything manual like what we are currently doing, and no extra code or config needs to be added to repos themselves. pdoc3 also has some really neat features like a live server for editing docs, and it can export to md/html/pdf. This requires a change in the release pipeline, and possibly a few non-functional tweaks to module source. I'll plan to add a CI check because pdoc will attempt to import everything even when it wouldn't be imported by default, and we have some hidden modules that aren't directly importable and will need to be fixed.

Second step, we've raised the idea of versioning our docs before. The default templates do not allow us to do that currently, but I think it would be very easy to modify the templates to have a header bar where we can add some branding, a version selector, and dark mode toggle for good measure. Since the version list will be dynamic, we can serve up a versions.json file or something and use javascript to parse it, or we could do something with frames if we want to avoid using JS unnecessarily.

Thoughts @ltfish @rhelmot @mborgerson?

**Comment by rhelmot** [comment]
Summary from an offline discussion:

go for it dude

**Comment by twizmwazin** [comment]
This is complete! Took less than a year, even.
