### ISSUE TITLE
Ubuntu 14.04, mkvirtualenv

### ISSUE THREAD

**Issue by haxmeadroom** [angr/angr-doc#45]
Minor change that might improve-
Ubuntu 14.04 doesn't appear to have `mkvirtualenv`.  Maybe express in the docs that `mkvirtualenv` can be simulated as well by..
```
virtualenv angr
. angr/bin/activate
```

**Comment by rhelmot** [comment]
That command is provided by `virtualenvwrapper`, which we mention as something you should install.

**Comment by rhelmot** [comment]
(the command won't show up unless you source, in your shell, /etc/bash_completion.d/virtualenvwrapper.sh, or something similar)

**Comment by haxmeadroom** [comment]
Sorry, I meant arch, not ubuntu.  I think this actually may be something specific to arch

**Comment by rhelmot** [comment]
https://www.archlinux.org/packages/community/any/python-virtualenvwrapper/

**Comment by haxmeadroom** [comment]
Ah.. my bad.. I'm a dumbass.  Yeah, on arch you have to source `/usr/bin/virtualenvwrapper.sh`  Thanks.
