### ISSUE TITLE
Add GDB Examples

### ISSUE THREAD

**Issue by Manouchehri** [angr/angr-doc#56]
Right now there's no examples of using gdb with angr. If you happen to have one you can share, please do. =)

**Comment by zardus** [comment]
@kereoz, could you make one from your gdb testcases maybe?

**Comment by Manouchehri** [comment]
@zardus As you were mentioning on IRC, is this what we need to use to load GDB core files? http://angr.io/api-doc/cle.html#cle.backends.elfcore.ELFCore

**Comment by rhelmot** [comment]
There are two components you can use - one is what you linked, which loads
core dumps and is not specific to GDB. The other, which lives in no
individual place but instead in a series of parameters, allows you to pass
in the output of certain GDB commands to control loading, such as the
output of "info proc mappings" controlling everyone's base addresses.

**Comment by Manouchehri** [comment]
Ah, so [simuvex.plugins.gdb.GDB](http://angr.io/api-doc/simuvex.html#simuvex.plugins.gdb.GDB) is the other component?

**Comment by rhelmot** [comment]
That's one of them! I had this:
https://github.com/angr/cle/blob/master/cle/loader.py#L59 in mind
specifically, but that definitely falls into the category of "poorly
documented features to deal with data from gdb"!

On Mon, May 23, 2016 at 2:01 PM, David Manouchehri <notifications@github.com

**Comment by Manouchehri** [comment]
From what I understand, I could avoid using CLE too, right? e.g. IDA or radare2 as the loader, and then use simuvex.plugins.gdb.GDB to set the stack/data/heap/regs.

(For context, I'm trying to think of ways to limit the amount of path finding angr has to do.)

**Comment by rhelmot** [comment]
..so you're never gonna get away with just Not Using CLE, but you could use a CLE backend that loads the binary using some other utility. In this case you'd still be able to use the `info proc mappings` stuff I pointed out before, since there's an interface between the CLE loader and the backends for requesting specific base addresses for various things.

Regardless, I'm not sure how the amount of pathfinding angr has to do is affected by how the binary is loaded.

**Comment by Manouchehri** [comment]
@rhelmot If I load the stack/data/heap/regs from a later 'state' that I've found manually, I can start angr at a later address, no?

**Comment by rhelmot** [comment]
Ah!!!! Yes. This is precisely the motivation for these mechanisms.

Either the coredump backend or a *combination* of the info proc mappings parameters and the simuvex plugin should be able to accomplish this.

**Comment by Manouchehri** [comment]
Here's a very vague question: what major differences are there between those two approaches?

**Comment by rhelmot** [comment]
To my knowledge, there is no functional difference :+)

They have different use cases, though. Core dumps are opaque, but easy to generate, while the info prints are more involved to generate, but live in a plain text format that you can tweak as needed.

**Comment by Manouchehri** [comment]
This stuff is quite exciting.

@rhelmot For driller, what kind of a commutation/database are you using to talk between angr and the fuzzer?

**Comment by rhelmot** [comment]
@NickStephens this is a question for you

**Comment by Manouchehri** [comment]
@P1kachu How far did you manage to get with this example? https://github.com/Manouchehri/angr-WIP/blob/5a395d5d28a39cab2dede44b1d16024901be51dc/dctf-2015/link-and-switch-200/r200.py#L91-L93

**Comment by P1kachu** [comment]
Ah, I haven't touched it in a while
But from what I remember, there were some problems with paths returning only errors.
I may check with the latest version of angr when I have some time

**Comment by Manouchehri** [comment]
Ah, so other than the state explosion, the gdb loading part is correct? I'll probably steal that script and modify it for another binary then.

**Comment by P1kachu** [comment]
Well I wouldn't be too sure about that.
But yes, testing it with another binary should be interesting.
If you do test it with a new one, I'll check it on angr-wip whenever I have some time !

**Comment by salls** [comment]
@Manouchehri For driller all you need to extract from AFL is the bitmap and the inputs, and these are on the file system. We used Redis for one version, and sqlite for another. Doesn't really matter what you use. All it does is transfer inputs back and forth. If you run on a single computer it could just be a process that reads from the filesystem occasionally

**Comment by KevinPoole** [comment]
> @rhelmot If I load the stack/data/heap/regs from a later 'state' that I've found manually, I can start angr at a later address, no?

I would like to do the above, and have successfully loaded an elf core dump using the elfcore back end. How do I now "run" the program forward from that state using angr? I realize this is a poor use of angr, but I wanted to first confirm that running it this way (with what I believe you would call a fully concretized starting point) yields the same result as when it was ran in the unicorn emulator, and then I was hoping to iterate back and "undefine" (set as symbolic?) portions of my starting state and start playing with it.

**Comment by rhelmot** [comment]
not related to this issue. this is an issue about angr's gdb plugin and how it lets you do the same thing as loading a coredump but in a less opaque way.
