### ISSUE TITLE
strcpy_test example no longer finds the password

### ISSUE THREAD

**Issue by inigofox** [angr/angr-doc#77]
When trying to run the example as is (from an up to date angr-dev docker image) the solve.py returns
"Totally not the password...@��@ �����"

**Comment by bananaappletw** [comment]
@inigofox 
Is this still exists?

**Comment by inigofox** [comment]
Based on the newest pull from angr-dev, this example is still broken as it's currently written.

**Comment by rhelmot** [comment]
So uh, the password is actually `Totally not the password...`, this example is working correctly. The garbage it's printing out afterwards is superfluous, and I will fix it now.
